// src/lib/pdf-generator.ts
// PURPOSE: Generates downloadable PDF reports for Lead Gen plans, SMM plans, and SMM analysis.
// Uses browser-native printing to PDF (no external library needed).
// Creates a hidden iframe with styled HTML, triggers print-to-PDF.

// ============================================================
// CORE: Generate PDF from HTML string
// ============================================================
export function downloadPDF(htmlContent: string, filename: string) {
  const printWindow = window.open('', '_blank', 'width=800,height=600');
  if (!printWindow) {
    alert('Please allow popups to download PDF');
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <style>
        @media print { @page { margin: 20mm 15mm; size: A4; } }
        body { font-family: 'Segoe UI', system-ui, sans-serif; color: #1a1a1a; line-height: 1.6; max-width: 750px; margin: 0 auto; padding: 20px; }
        h1 { color: #1B4332; font-size: 24px; border-bottom: 3px solid #2DD4A8; padding-bottom: 8px; margin-top: 30px; }
        h2 { color: #1B4332; font-size: 18px; margin-top: 24px; border-bottom: 1px solid #e0e0e0; padding-bottom: 4px; }
        h3 { color: #333; font-size: 14px; margin-top: 16px; }
        .header { text-align: center; margin-bottom: 30px; padding: 20px; background: linear-gradient(135deg, #1B4332, #2DD4A8); color: white; border-radius: 8px; }
        .header h1 { color: white; border: none; margin: 0; font-size: 28px; }
        .header p { color: #d0f0e0; margin: 5px 0 0; font-size: 14px; }
        .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 16px 0; }
        .kpi-card { background: #f8faf9; border: 1px solid #e0e0e0; border-radius: 8px; padding: 12px; text-align: center; }
        .kpi-card .value { font-size: 22px; font-weight: bold; color: #1B4332; }
        .kpi-card .label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
        .field-row { display: flex; justify-content: space-between; padding: 8px 12px; border-bottom: 1px solid #f0f0f0; }
        .field-label { color: #666; font-size: 12px; width: 40%; }
        .field-value { color: #1a1a1a; font-size: 13px; font-weight: 500; width: 58%; text-align: right; }
        .section { background: #f8faf9; border-radius: 8px; padding: 16px; margin: 12px 0; border: 1px solid #e8e8e8; }
        .tag { display: inline-block; background: #e8f5e9; color: #1B4332; padding: 3px 10px; border-radius: 12px; font-size: 11px; margin: 2px 4px 2px 0; }
        .prompt-box { background: #f3e8ff; border: 1px solid #d8b4fe; border-radius: 8px; padding: 12px; margin: 8px 0; font-size: 11px; line-height: 1.5; white-space: pre-wrap; word-break: break-word; }
        .checklist-item { padding: 4px 0; font-size: 13px; }
        .checklist-item::before { content: '☐ '; color: #2DD4A8; }
        .calendar-row { display: grid; grid-template-columns: 80px 70px 1fr; gap: 8px; padding: 10px 0; border-bottom: 1px solid #f0f0f0; align-items: start; }
        .cal-date { font-weight: bold; font-size: 13px; color: #1B4332; }
        .cal-type { font-size: 11px; padding: 2px 8px; border-radius: 10px; background: #e8f5e9; color: #1B4332; text-align: center; }
        .cal-topic { font-size: 13px; }
        .score-badge { display: inline-block; padding: 4px 12px; border-radius: 16px; font-weight: bold; font-size: 14px; }
        .score-green { background: #dcfce7; color: #166534; }
        .score-yellow { background: #fef9c3; color: #854d0e; }
        .score-red { background: #fee2e2; color: #991b1b; }
        .footer { text-align: center; margin-top: 40px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 11px; color: #999; }
        .page-break { page-break-before: always; }
      </style>
    </head>
    <body>
      ${htmlContent}
      <div class="footer">
        Generated by NH Marketing Command Center | ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
      </div>
    </body>
    </html>
  `);

  printWindow.document.close();
  setTimeout(() => {
    printWindow.print();
  }, 500);
}

// ============================================================
// LEAD GEN CAMPAIGN PLAN PDF
// ============================================================
export function generateLeadGenPDF(data: {
  strategy?: any;
  creatives?: any;
  adReview?: any;
  adConfig?: any;
  projectName: string;
  budget?: string;
}) {
  let html = `
    <div class="header">
      <h1>Campaign Plan</h1>
      <p>${data.projectName} | Neelachala Homes</p>
    </div>
  `;

  // Strategy section
  if (data.strategy) {
    html += '<h1>Campaign Strategy</h1>';
    if (data.strategy.overview) html += '<div class="section"><p>' + data.strategy.overview + '</p></div>';
    if (data.strategy.budgetAdvice) html += '<div class="section" style="border-left:3px solid #eab308;"><p>' + data.strategy.budgetAdvice + '</p></div>';

    if (data.strategy.campaigns) {
      data.strategy.campaigns.forEach((camp: any, i: number) => {
        html += '<h2>' + (camp.project || 'Campaign ' + (i + 1)) + ' — ' + (camp.funnelStage || 'BOFU') + '</h2>';
        const fields = ['campaignName', 'adType', 'campaignObjective', 'locations', 'ageRange', 'gender', 'detailedTargeting', 'dailyBudget', 'duration', 'bidStrategy', 'primaryText', 'headline', 'description', 'callToAction', 'icebreaker1', 'icebreaker2', 'icebreaker3'];
        fields.forEach(f => {
          const val = camp[f];
          if (val) {
            const v = typeof val === 'object' ? val.v : val;
            if (v) html += '<div class="field-row"><span class="field-label">' + f.replace(/([A-Z])/g, ' $1').trim() + '</span><span class="field-value">' + v + '</span></div>';
          }
        });
      });
    }

    if (data.strategy.immediateActions) {
      html += '<h2>Immediate Actions</h2>';
      data.strategy.immediateActions.forEach((a: string) => {
        html += '<div class="checklist-item">' + a + '</div>';
      });
    }
  }

  // Quick generate (single ad)
  if (data.strategy?.idea) {
    html += '<h1>Ad Details</h1>';
    html += '<div class="section"><strong>Concept:</strong> ' + data.strategy.idea + '</div>';
    
    html += '<h2>Ad Copy</h2>';
    if (data.strategy.primaryText) html += '<div class="field-row"><span class="field-label">Primary Text</span><span class="field-value">' + data.strategy.primaryText + '</span></div>';
    if (data.strategy.primaryTextOdia) html += '<div class="field-row"><span class="field-label">Odia</span><span class="field-value">' + data.strategy.primaryTextOdia + '</span></div>';
    if (data.strategy.headline) html += '<div class="field-row"><span class="field-label">Headline</span><span class="field-value">' + data.strategy.headline + '</span></div>';
    if (data.strategy.description) html += '<div class="field-row"><span class="field-label">Description</span><span class="field-value">' + data.strategy.description + '</span></div>';

    html += '<h2>Ad Configuration</h2>';
    ['objective', 'adType', 'locations', 'ageRange', 'gender', 'interests', 'behaviors', 'placements', 'dailyBudget', 'duration', 'bidStrategy'].forEach(f => {
      if (data.strategy[f]) html += '<div class="field-row"><span class="field-label">' + f + '</span><span class="field-value">' + data.strategy[f] + '</span></div>';
    });

    if (data.strategy.icebreakers) {
      html += '<h2>Icebreakers</h2>';
      data.strategy.icebreakers.forEach((ib: string) => html += '<div class="field-row"><span class="field-value" style="width:100%;text-align:left;">' + ib + '</span></div>');
    }

    if (data.strategy.creativePrompt) {
      html += '<h2>Creative Prompt (1080×1080)</h2>';
      html += '<div class="prompt-box">' + data.strategy.creativePrompt + '</div>';
    }
    if (data.strategy.creativePromptStory) {
      html += '<h2>Creative Prompt (Story 1080×1920)</h2>';
      html += '<div class="prompt-box">' + data.strategy.creativePromptStory + '</div>';
    }

    if (data.strategy.launchChecklist) {
      html += '<h2>Launch Checklist</h2>';
      data.strategy.launchChecklist.forEach((s: string) => html += '<div class="checklist-item">' + s + '</div>');
    }
  }

  // Creatives section
  if (data.creatives?.variants) {
    html += '<div class="page-break"></div><h1>Creative Variants</h1>';
    if (data.creatives.strategy) html += '<div class="section">' + data.creatives.strategy + '</div>';
    data.creatives.variants.forEach((v: any) => {
      html += '<h2>Variant ' + v.variant + ' — ' + v.angle + '</h2>';
      html += '<div class="field-row"><span class="field-label">Format</span><span class="field-value">' + v.format + '</span></div>';
      html += '<div class="field-row"><span class="field-label">Primary Text</span><span class="field-value">' + (v.primaryText || '') + '</span></div>';
      html += '<div class="field-row"><span class="field-label">Headline</span><span class="field-value">' + (v.headline || '') + '</span></div>';
      if (v.nanoPrompt) html += '<h3>Nanobanana Prompt</h3><div class="prompt-box">' + v.nanoPrompt + '</div>';
    });
  }

  // Ad Review section
  if (data.adReview?.overallScore) {
    html += '<div class="page-break"></div><h1>Creative Review</h1>';
    const sc = data.adReview.overallScore >= 8 ? 'green' : data.adReview.overallScore >= 5 ? 'yellow' : 'red';
    html += '<p>Score: <span class="score-badge score-' + sc + '">' + data.adReview.overallScore + '/10</span> — ' + (data.adReview.verdict || '') + '</p>';
    if (data.adReview.issues) {
      html += '<h2>Issues</h2>';
      data.adReview.issues.forEach((iss: any) => {
        html += '<div class="field-row"><span class="field-label">[' + iss.severity + '] ' + iss.area + '</span><span class="field-value">' + iss.issue + '<br/>Fix: ' + iss.fix + '</span></div>';
      });
    }
  }

  downloadPDF(html, 'NH_Campaign_Plan_' + data.projectName.replace(/\s/g, '_'));
}

// ============================================================
// SMM PLAN PDF
// ============================================================
export function generateSMMPlanPDF(data: {
  overview: string;
  contentMix: any;
  pillars: any[];
  calendar: any[];
  kpiTargets: any;
  duration: string;
}) {
  let html = `
    <div class="header">
      <h1>Social Media Content Plan</h1>
      <p>${data.duration} | Neelachala Homes</p>
    </div>
  `;

  html += '<h1>Overview</h1>';
  html += '<div class="section"><p>' + data.overview + '</p></div>';

  if (data.contentMix) {
    html += '<h2>Content Mix</h2>';
    html += '<div class="kpi-grid">';
    Object.entries(data.contentMix).forEach(([type, count]) => {
      html += '<div class="kpi-card"><div class="value">' + count + '</div><div class="label">' + type.replace(/([A-Z])/g, ' $1') + '</div></div>';
    });
    html += '</div>';
  }

  if (data.pillars) {
    html += '<h2>Content Pillars</h2>';
    data.pillars.forEach((p: any) => {
      html += '<div class="field-row"><span class="field-label"><strong>' + p.pillar + '</strong> (' + p.freq + ')</span><span class="field-value">' + p.purpose + '</span></div>';
    });
  }

  if (data.kpiTargets) {
    html += '<h2>KPI Targets</h2>';
    Object.entries(data.kpiTargets).forEach(([k, v]) => {
      html += '<div class="field-row"><span class="field-label">' + k.replace(/([A-Z])/g, ' $1') + '</span><span class="field-value">' + v + '</span></div>';
    });
  }

  if (data.calendar && data.calendar.length > 0) {
    html += '<div class="page-break"></div><h1>Content Calendar</h1>';
    data.calendar.forEach((post: any) => {
      html += '<div class="calendar-row">';
      html += '<div class="cal-date">' + post.date + '<br/><small>' + (post.day || '') + '</small></div>';
      html += '<div class="cal-type">' + (post.type || '') + '</div>';
      html += '<div class="cal-topic"><strong>' + (post.topic || '') + '</strong>';
      if (post.time) html += '<br/><small>Post at ' + post.time + ' on ' + (post.platform || 'both') + '</small>';
      html += '</div></div>';
    });

    // Detailed posts
    html += '<div class="page-break"></div><h1>Post Details</h1>';
    data.calendar.forEach((post: any, i: number) => {
      html += '<h2>' + post.date + ' — ' + (post.topic || 'Post ' + (i + 1)) + '</h2>';
      html += '<div class="field-row"><span class="field-label">Type</span><span class="field-value">' + (post.type || '') + ' on ' + (post.platform || 'both') + '</span></div>';
      html += '<div class="field-row"><span class="field-label">Time</span><span class="field-value">' + (post.time || '') + '</span></div>';
      if (post.captionEn) html += '<div class="section"><strong>Caption:</strong><br/>' + post.captionEn + '</div>';
      if (post.hashtags) html += '<p>' + post.hashtags.map((h: string) => '<span class="tag">#' + h + '</span>').join('') + '</p>';
      if (post.nanoPrompt) html += '<div class="prompt-box">' + post.nanoPrompt + '</div>';
      if (post.reelScript) html += '<div class="section"><strong>Reel Script:</strong><br/>' + post.reelScript + '</div>';
    });
  }

  downloadPDF(html, 'NH_SMM_Plan_' + data.duration.replace(/\s/g, '_'));
}

// ============================================================
// SMM ANALYZER REPORT PDF
// ============================================================
export function generateSMMReportPDF(data: {
  platform: string;
  period: string;
  analysis: any;
  metrics: any;
}) {
  let html = `
    <div class="header">
      <h1>Social Media Performance Report</h1>
      <p>${data.platform} | ${data.period} | Neelachala Homes</p>
    </div>
  `;

  if (data.analysis?.healthScore) {
    const sc = data.analysis.healthScore >= 7 ? 'green' : data.analysis.healthScore >= 4 ? 'yellow' : 'red';
    html += '<h1>Overall Health</h1>';
    html += '<p>Score: <span class="score-badge score-' + sc + '">' + data.analysis.healthScore + '/10</span></p>';
    html += '<div class="section"><p>' + (data.analysis.assessment || '') + '</p></div>';
  }

  if (data.analysis?.scorecard) {
    html += '<h2>Metrics Scorecard</h2>';
    data.analysis.scorecard.forEach((s: any) => {
      html += '<div class="field-row"><span class="field-label">' + s.metric + '</span><span class="field-value">' + s.value + ' (benchmark: ' + s.benchmark + ') [' + s.status.toUpperCase() + ']</span></div>';
    });
  }

  if (data.analysis?.contentPerformance) {
    html += '<h2>Content Performance</h2>';
    html += '<div class="section">';
    html += '<p><strong>Best:</strong> ' + data.analysis.contentPerformance.bestType + '</p>';
    html += '<p><strong>Worst:</strong> ' + data.analysis.contentPerformance.worstType + '</p>';
    html += '<p><strong>Recommendation:</strong> ' + data.analysis.contentPerformance.recommendation + '</p>';
    html += '</div>';
  }

  if (data.analysis?.timingAnalysis) {
    html += '<h2>Timing Analysis</h2>';
    html += '<div class="section">';
    html += '<p><strong>Best Day:</strong> ' + data.analysis.timingAnalysis.bestDay + ' at ' + data.analysis.timingAnalysis.bestTime + '</p>';
    html += '<p><strong>Recommendation:</strong> ' + data.analysis.timingAnalysis.recommendation + '</p>';
    html += '</div>';
  }

  if (data.analysis?.suggestions) {
    html += '<h2>Recommendations</h2>';
    data.analysis.suggestions.forEach((s: string) => {
      html += '<div class="checklist-item">' + s + '</div>';
    });
  }

  if (data.analysis?.kpiTargets) {
    html += '<h2>Next Period Targets</h2>';
    Object.entries(data.analysis.kpiTargets).forEach(([k, v]) => {
      html += '<div class="field-row"><span class="field-label">' + k.replace(/([A-Z])/g, ' $1') + '</span><span class="field-value">' + v + '</span></div>';
    });
  }

  downloadPDF(html, 'NH_SMM_Report_' + data.platform + '_' + data.period.replace(/\s/g, '_'));
}